package rs.moma.gui;

import rs.moma.entities.ZakazaniTretman;
import rs.moma.entities.Zaposlen;
import rs.moma.gui.helper.NoSelectionModel;
import rs.moma.managers.Klijenti;
import rs.moma.managers.Tretmani;
import rs.moma.entities.Klijent;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class KozmeticarPage extends KalendarForm {
    private       JList<String> tretmaniList;
    private       JScrollPane   kalendarPane;
    private       JTable        kalendarTbl;
    private       JTable        tretmaniTbl;
    private       JPanel        mainPanel;
    private       JLabel        mesecLbl;
    private       JButton       rightBtn;
    private       JButton       leftBtn;
    private final Zaposlen      kozmeticar;

    public KozmeticarPage(Zaposlen kozmeticar) {
        super(false);
        this.kozmeticar = kozmeticar;

        $$$setupUI$$$();
        setSize(1050, 1000);
        setContentPane(mainPanel);
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(750, 800));
        setTitle(kozmeticar.Ime + " " + kozmeticar.Prezime);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        tretmaniList.setSelectionModel(new NoSelectionModel());
        tretmaniList.setListData(kozmeticar.getTretmani().stream().map(tretman -> tretman.Naziv).sorted().toArray(String[]::new));
        super.setup(kalendarPane, tretmaniTbl, 200, kalendarTbl, mesecLbl, rightBtn, leftBtn, false, false);

        setVisible(true);
    }

    protected ArrayList<ZakazaniTretman> getTretmani() {
        return kozmeticar.getZakazaniTretmani();
    }

    protected String[][] tretmanToList(ZakazaniTretman tretman) {
        Klijent klijent = new Klijenti().get(tretman.KlijentID);
        return new String[][]{{}, {"Vreme: ", tretman.Vreme.getHour() + "h"},
                              {"Klijent: ", klijent.getDisplayName()},
                              {"Tretman: ", new Tretmani().get(tretman.TretmanID).Naziv},
                              {"Trajanje: ", tretman.Trajanje + " minuta"}};
    }

    @Override
    protected void updatePage() {}

    private void createUIComponents() {
        kalendarTbl = super.makeKalendarTable();
    }
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setMinimumSize(new Dimension(308, 412));
        GridBagConstraints gbc;
        gbc        = new GridBagConstraints();
        gbc.gridx  = 1;
        gbc.gridy  = 1;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill   = GridBagConstraints.HORIZONTAL;
        mainPanel.add(panel1, gbc);
        leftBtn = new JButton();
        leftBtn.setFocusPainted(false);
        leftBtn.setIcon(new ImageIcon(getClass().getResource("/left.png")));
        leftBtn.setPreferredSize(new Dimension(38, 38));
        leftBtn.setText("");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        panel1.add(leftBtn, gbc);
        rightBtn = new JButton();
        rightBtn.setFocusPainted(false);
        rightBtn.setIcon(new ImageIcon(getClass().getResource("/right.png")));
        rightBtn.setPreferredSize(new Dimension(38, 38));
        rightBtn.setText("");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 2;
        gbc.gridy  = 0;
        gbc.anchor = GridBagConstraints.NORTHEAST;
        panel1.add(rightBtn, gbc);
        mesecLbl = new JLabel();
        mesecLbl.setHorizontalAlignment(0);
        mesecLbl.setHorizontalTextPosition(0);
        mesecLbl.setText("Januar");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 1;
        gbc.gridy   = 0;
        gbc.weightx = 1.0;
        gbc.fill    = GridBagConstraints.BOTH;
        panel1.add(mesecLbl, gbc);
        kalendarPane  = new JScrollPane();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 2;
        gbc.gridwidth = 3;
        gbc.anchor    = GridBagConstraints.NORTH;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        panel1.add(kalendarPane, gbc);
        kalendarTbl.setCellSelectionEnabled(true);
        kalendarTbl.setColumnSelectionAllowed(true);
        kalendarTbl.setDragEnabled(false);
        kalendarTbl.setFocusable(false);
        kalendarTbl.setPreferredScrollableViewportSize(new Dimension(300, 300));
        kalendarTbl.setSelectionBackground(new Color(-11833681));
        kalendarTbl.setShowHorizontalLines(true);
        kalendarTbl.setShowVerticalLines(true);
        kalendarPane.setViewportView(kalendarTbl);
        final JPanel spacer1 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 1;
        gbc.gridwidth = 3;
        gbc.anchor    = GridBagConstraints.NORTH;
        gbc.ipady     = 5;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 2;
        gbc.gridy      = 1;
        gbc.gridheight = 3;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 30;
        mainPanel.add(spacer2, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setMinimumSize(new Dimension(300, 57));
        gbc            = new GridBagConstraints();
        gbc.gridx      = 3;
        gbc.gridy      = 1;
        gbc.gridheight = 3;
        gbc.weightx    = 2.0;
        gbc.weighty    = 1.0;
        gbc.fill       = GridBagConstraints.BOTH;
        mainPanel.add(panel2, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setPreferredSize(new Dimension(58, 38));
        label1.setText("Raspored");
        gbc       = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill  = GridBagConstraints.HORIZONTAL;
        panel2.add(label1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill    = GridBagConstraints.BOTH;
        panel2.add(scrollPane1, gbc);
        tretmaniTbl = new JTable();
        tretmaniTbl.setFocusable(false);
        tretmaniTbl.setShowHorizontalLines(true);
        tretmaniTbl.setShowVerticalLines(true);
        scrollPane1.setViewportView(tretmaniTbl);
        final JPanel spacer3 = new JPanel();
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 1;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.ipady  = 5;
        panel2.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 4;
        gbc.gridy      = 1;
        gbc.gridheight = 3;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 30;
        mainPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 0;
        gbc.gridy      = 1;
        gbc.gridheight = 3;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 30;
        mainPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 0;
        gbc.gridwidth = 5;
        gbc.fill      = GridBagConstraints.VERTICAL;
        gbc.ipady     = 30;
        mainPanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 4;
        gbc.gridwidth = 5;
        gbc.fill      = GridBagConstraints.VERTICAL;
        gbc.ipady     = 30;
        mainPanel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc        = new GridBagConstraints();
        gbc.gridx  = 1;
        gbc.gridy  = 2;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.ipady  = 10;
        mainPanel.add(spacer8, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc         = new GridBagConstraints();
        gbc.gridx   = 1;
        gbc.gridy   = 3;
        gbc.weightx = 2.0;
        gbc.fill    = GridBagConstraints.BOTH;
        mainPanel.add(panel3, gbc);
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(0);
        label2.setHorizontalTextPosition(0);
        label2.setPreferredSize(new Dimension(74, 38));
        label2.setText("Zaduženja");
        gbc       = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill  = GridBagConstraints.BOTH;
        panel3.add(label2, gbc);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill    = GridBagConstraints.BOTH;
        panel3.add(scrollPane2, gbc);
        tretmaniList = new JList();
        tretmaniList.setAutoscrolls(true);
        tretmaniList.setEnabled(true);
        tretmaniList.setFocusable(false);
        scrollPane2.setViewportView(tretmaniList);
        final JPanel spacer9 = new JPanel();
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 1;
        gbc.anchor = GridBagConstraints.NORTH;
        panel3.add(spacer9, gbc);
        mesecLbl.setLabelFor(kalendarPane);
        label1.setLabelFor(scrollPane1);
        label2.setLabelFor(scrollPane2);
    }
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return mainPanel;}
}
