package rs.moma.gui;

import rs.moma.entities.Klijent;
import rs.moma.entities.Zaposlen;
import rs.moma.managers.Klijenti;
import rs.moma.managers.Zaposleni;

import javax.swing.*;

import java.awt.*;

import static javax.swing.JOptionPane.showMessageDialog;
import static rs.moma.helper.DataTools.*;

public class LoginForm extends JDialog {
    private JPanel         loginPanel;
    private JTextField     usernameTxt;
    private JPasswordField passwordTxt;
    private JButton        prijavaBtn;

    public LoginForm(WelcomePage parent) {
        super(parent, "Prijava", true);
        setContentPane(loginPanel);
        setSize(500, 350);
        setLocationRelativeTo(parent);
        prijavaBtn.addActionListener(e -> {
            if (!isInputFilled(usernameTxt, passwordTxt))
                showMessageDialog(this, "Popunite sva polja!");
            else if (!isInputValid(usernameTxt, passwordTxt))
                showMessageDialog(this, "Neispravan unos!");
            else {
                Klijent  klijent  = new Klijenti().prijava(usernameTxt.getText(), passwordTxt.getText());
                Zaposlen zaposlen = new Zaposleni().prijava(usernameTxt.getText(), passwordTxt.getText());
                if (klijent == null && zaposlen == null)
                    showMessageDialog(this, "Neispravno ime ili šifra!");
                else {
                    setVisible(false);
                    dispose();
                    parent.setVisible(false);
                }
                if (zaposlen != null) {
                    if (zaposlen.TipZaposlenog == ETipZaposlenog.KOZMETICAR)
                        new KozmeticarPage(zaposlen, parent);
                    else if (zaposlen.TipZaposlenog == ETipZaposlenog.MENADZER)
                        new MenadzerPage(zaposlen, parent);
                    else if (zaposlen.TipZaposlenog == ETipZaposlenog.RECEPCIONER)
                        new RecepcionerPage(zaposlen, parent);
                } else if (klijent != null) {
                    new KlijentPage(klijent, parent);
                }
            }
        });
        setVisible(true);
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginPanel = new JPanel();
        loginPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Korisničko ime:");
        GridBagConstraints gbc;
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 0;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        loginPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Lozinka:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 1;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        loginPanel.add(label2, gbc);
        usernameTxt = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 0;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        loginPanel.add(usernameTxt, gbc);
        final JPanel spacer1 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 2;
        gbc.gridwidth = 4;
        gbc.fill      = GridBagConstraints.VERTICAL;
        gbc.ipady     = 30;
        loginPanel.add(spacer1, gbc);
        prijavaBtn = new JButton();
        prijavaBtn.setFocusPainted(false);
        prijavaBtn.setFocusable(true);
        prijavaBtn.setMargin(new Insets(0, 0, 0, 0));
        prijavaBtn.setPreferredSize(new Dimension(200, 50));
        prijavaBtn.setText("Prijavi se");
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 3;
        gbc.gridwidth = 4;
        loginPanel.add(prijavaBtn, gbc);
        passwordTxt = new JPasswordField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 1;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        loginPanel.add(passwordTxt, gbc);
        final JPanel spacer2 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 1;
        gbc.gridy      = 0;
        gbc.gridheight = 2;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 30;
        loginPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 3;
        gbc.gridy      = 0;
        gbc.gridheight = 2;
        gbc.weightx    = 0.5;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        loginPanel.add(spacer3, gbc);
        label1.setLabelFor(usernameTxt);
        label2.setLabelFor(passwordTxt);
    }
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return loginPanel;}
}

