package rs.moma.gui;

import rs.moma.gui.helper.NameValue;
import rs.moma.helper.DataTools.EPol;
import rs.moma.entities.Klijent;
import rs.moma.managers.Klijenti;

import javax.swing.*;

import java.awt.*;

import static javax.swing.JOptionPane.showMessageDialog;
import static rs.moma.helper.DataTools.*;

public class RegisterForm extends JDialog {
    final   Klijenti       klijenti = new Klijenti();
    private JButton        registracijaBtn;
    private JPanel         registerPanel;
    private JTextField     usernameTxt;
    private JPasswordField passwordTxt;
    private JTextField     prezimeTxt;
    private JTextField     telefonTxt;
    private JTextField     adresaTxt;
    private JTextField     imeTxt;
    private JComboBox<NameValue> polBox;

    public RegisterForm(JFrame parent) {
        super(parent, "Registracija", true);
        setContentPane(registerPanel);
        setSize(600, 600);
        setLocationRelativeTo(parent);
        polBox.setModel(new DefaultComboBoxModel(new Object[]{new NameValue("Muško", EPol.MALE), new NameValue("Žensko", EPol.FEMALE), new NameValue("Ostalo", EPol.OTHER)}));
        registracijaBtn.addActionListener(e -> {
            if (!isInputValid(imeTxt, prezimeTxt, telefonTxt, adresaTxt, usernameTxt, passwordTxt))
                showMessageDialog(this, "Neispravan unos!");
            else if (!klijenti.isUsernameFree(usernameTxt.getText()))
                showMessageDialog(this, "Uneto korisničko ime je zauzeto!");
            else if (isInputFilled(imeTxt, prezimeTxt, telefonTxt, adresaTxt, usernameTxt, passwordTxt)) {
                klijenti.add(new Klijent(imeTxt.getText(),
                                         prezimeTxt.getText(),
                                         (EPol) getSelectedValue(polBox),
                                         telefonTxt.getText(),
                                         adresaTxt.getText(),
                                         usernameTxt.getText(),
                                         passwordTxt.getText()));
                setVisible(false);
                dispose();
            } else
                showMessageDialog(this, "Popunite sva polja!");
        });
        setVisible(true);
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        registerPanel = new JPanel();
        registerPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Ime:");
        GridBagConstraints gbc;
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 1;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        registerPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Prezime:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 2;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        registerPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Pol:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 3;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        registerPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Telefon:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 4;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        registerPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Adresa:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 5;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        registerPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Korisničko ime:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 6;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        registerPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Lozinka:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 7;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        registerPanel.add(label7, gbc);
        final JPanel spacer1 = new JPanel();
        gbc       = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill  = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 30;
        registerPanel.add(spacer1, gbc);
        imeTxt = new JTextField();
        imeTxt.setMaximumSize(new Dimension(385, 2147483647));
        imeTxt.setMinimumSize(new Dimension(385, 30));
        imeTxt.setPreferredSize(new Dimension(385, 30));
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 1;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        registerPanel.add(imeTxt, gbc);
        prezimeTxt = new JTextField();
        prezimeTxt.setMaximumSize(new Dimension(385, 2147483647));
        prezimeTxt.setMinimumSize(new Dimension(385, 30));
        prezimeTxt.setPreferredSize(new Dimension(385, 30));
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 2;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        registerPanel.add(prezimeTxt, gbc);
        polBox = new JComboBox();
        polBox.setMaximumSize(new Dimension(385, 32767));
        polBox.setMinimumSize(new Dimension(385, 30));
        polBox.setPreferredSize(new Dimension(385, 30));
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 3;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        registerPanel.add(polBox, gbc);
        telefonTxt = new JTextField();
        telefonTxt.setMaximumSize(new Dimension(385, 2147483647));
        telefonTxt.setMinimumSize(new Dimension(385, 30));
        telefonTxt.setPreferredSize(new Dimension(385, 30));
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 4;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        registerPanel.add(telefonTxt, gbc);
        adresaTxt = new JTextField();
        adresaTxt.setMaximumSize(new Dimension(385, 2147483647));
        adresaTxt.setMinimumSize(new Dimension(385, 30));
        adresaTxt.setPreferredSize(new Dimension(385, 30));
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 5;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        registerPanel.add(adresaTxt, gbc);
        usernameTxt = new JTextField();
        usernameTxt.setMaximumSize(new Dimension(385, 2147483647));
        usernameTxt.setMinimumSize(new Dimension(385, 30));
        usernameTxt.setPreferredSize(new Dimension(385, 30));
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 6;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        registerPanel.add(usernameTxt, gbc);
        final JPanel spacer2 = new JPanel();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 3;
        gbc.gridy   = 0;
        gbc.weightx = 0.5;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc       = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill  = GridBagConstraints.VERTICAL;
        gbc.ipady = 70;
        registerPanel.add(spacer3, gbc);
        registracijaBtn = new JButton();
        registracijaBtn.setFocusPainted(false);
        registracijaBtn.setMargin(new Insets(0, 0, 0, 0));
        registracijaBtn.setPreferredSize(new Dimension(200, 50));
        registracijaBtn.setText("Registruj se");
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 9;
        gbc.gridwidth = 4;
        registerPanel.add(registracijaBtn, gbc);
        passwordTxt = new JPasswordField();
        passwordTxt.setMaximumSize(new Dimension(385, 2147483647));
        passwordTxt.setMinimumSize(new Dimension(385, 30));
        passwordTxt.setPreferredSize(new Dimension(385, 30));
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 7;
        gbc.weightx = 2.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        gbc.insets  = new Insets(5, 0, 5, 0);
        registerPanel.add(passwordTxt, gbc);
        label1.setLabelFor(imeTxt);
        label2.setLabelFor(prezimeTxt);
        label3.setLabelFor(polBox);
        label4.setLabelFor(telefonTxt);
        label5.setLabelFor(adresaTxt);
        label6.setLabelFor(usernameTxt);
        label7.setLabelFor(passwordTxt);
    }
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return registerPanel;}
}