package rs.moma.gui;

import rs.moma.gui.helper.NameValue;
import rs.moma.entities.Klijent;
import rs.moma.managers.Klijenti;

import javax.swing.*;

import java.awt.*;

import static javax.swing.JOptionPane.showMessageDialog;
import static rs.moma.helper.DataTools.*;

public class RegisterForm extends JDialog {
    private JButton              registracijaBtn;
    private JPanel               registerPanel;
    private JTextField           usernameTxt;
    private JPasswordField       passwordTxt;
    private JTextField           prezimeTxt;
    private JTextField           telefonTxt;
    private JTextField           adresaTxt;
    private JTextField           imeTxt;
    private JComboBox<NameValue> polBox;

    public RegisterForm(JFrame parent) {
        super(parent, "Registracija", true);
        setMinimumSize(new Dimension(560, 560));
        setContentPane(registerPanel);
        setSize(600, 600);
        setLocationRelativeTo(parent);
        fillPolBox(polBox);
        registracijaBtn.addActionListener(e -> {
            Klijenti klijenti = new Klijenti();
            if (!isInputValid(imeTxt, prezimeTxt, telefonTxt, adresaTxt, usernameTxt, passwordTxt))
                showMessageDialog(this, "Neispravan unos!");
            else if (klijenti.isUsernameTaken(usernameTxt.getText()))
                showMessageDialog(this, "Uneto korisničko ime je zauzeto!");
            else if (isInputFilled(imeTxt, prezimeTxt, telefonTxt, adresaTxt, usernameTxt, passwordTxt)) {
                klijenti.add(new Klijent(imeTxt.getText(),
                                         prezimeTxt.getText(),
                                         (EPol) getSelectedValue(polBox),
                                         telefonTxt.getText(),
                                         adresaTxt.getText(),
                                         usernameTxt.getText(),
                                         passwordTxt.getText()));
                setVisible(false);
                dispose();
            } else
                showMessageDialog(this, "Popunite sva polja!");
        });
        setVisible(true);
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        registerPanel = new JPanel();
        registerPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Ime:");
        GridBagConstraints gbc;
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 1;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        registerPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Prezime:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 2;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        registerPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Pol:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 3;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        registerPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Telefon:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 4;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        registerPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Adresa:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 5;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        registerPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Korisničko ime:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 6;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        registerPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Lozinka:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 7;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        registerPanel.add(label7, gbc);
        imeTxt      = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 1;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(imeTxt, gbc);
        prezimeTxt  = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 2;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(prezimeTxt, gbc);
        polBox      = new JComboBox();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 3;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(polBox, gbc);
        telefonTxt  = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 4;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(telefonTxt, gbc);
        adresaTxt   = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 5;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(adresaTxt, gbc);
        usernameTxt = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 6;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(usernameTxt, gbc);
        passwordTxt = new JPasswordField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 7;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(passwordTxt, gbc);
        final JPanel spacer1 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 1;
        gbc.gridy      = 1;
        gbc.gridheight = 7;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 20;
        registerPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 0;
        gbc.gridwidth = 4;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        registerPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 10;
        gbc.gridwidth = 4;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        registerPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 8;
        gbc.gridwidth = 3;
        gbc.fill      = GridBagConstraints.VERTICAL;
        gbc.ipady     = 20;
        registerPanel.add(spacer4, gbc);
        registracijaBtn = new JButton();
        registracijaBtn.setFocusPainted(false);
        registracijaBtn.setMargin(new Insets(0, 0, 0, 0));
        registracijaBtn.setPreferredSize(new Dimension(200, 50));
        registracijaBtn.setText("Registruj se");
        gbc       = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill  = GridBagConstraints.HORIZONTAL;
        registerPanel.add(registracijaBtn, gbc);
        final JPanel spacer5 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 3;
        gbc.gridy      = 1;
        gbc.gridheight = 9;
        gbc.weightx    = 3.0;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        registerPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 9;
        gbc.weightx = 2.0;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        registerPanel.add(spacer6, gbc);
        label1.setLabelFor(imeTxt);
        label2.setLabelFor(prezimeTxt);
        label3.setLabelFor(polBox);
        label4.setLabelFor(telefonTxt);
        label5.setLabelFor(adresaTxt);
        label6.setLabelFor(usernameTxt);
        label7.setLabelFor(passwordTxt);
    }
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return registerPanel;}
}