package rs.moma.gui.crud;

import rs.moma.entities.ZakazaniTretman;
import rs.moma.gui.helper.DateKeyAdapter;
import rs.moma.gui.helper.NameValue;
import rs.moma.gui.helper.NumericKeyAdapter;
import rs.moma.gui.helper.TimeKeyAdapter;
import rs.moma.managers.Klijenti;
import rs.moma.managers.Tretmani;
import rs.moma.managers.ZakazaniTretmani;
import rs.moma.managers.Zaposleni;

import javax.swing.*;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;

import static javax.swing.JOptionPane.showMessageDialog;
import static rs.moma.helper.DataTools.*;
import static rs.moma.helper.DataTools.EStanjeTermina.*;

public class EditZakazaniTretmanForm extends JDialog {
    private JCheckBox            karticaLojalnostiCB;
    private JComboBox<NameValue> kozmeticarBox;
    private JTextField           trajanjeTxt;
    private JComboBox<NameValue> tretmanBox;
    private JComboBox<NameValue> klijentBox;
    private JPanel               mainPanel;
    private JComboBox<NameValue> stanjeBox;
    private JTextField           datumTxt;
    private JTextField           vremeTxt;
    private JButton              saveBtn;
    private JTextField           cenaTxt;

    public EditZakazaniTretmanForm(JFrame parent, ZakazaniTretman tretman, Runnable update) {
        super(parent, tretman != null ? "Zakazani tretman: " + new Tretmani().get(tretman.TretmanID).Naziv : "Dodavanje zakazanog tretmana", true);
        setMinimumSize(new Dimension(550, 670));
        setSize(900, 750);
        setLocationRelativeTo(parent);
        setContentPane(mainPanel);

        tretmanBox.setModel(new DefaultComboBoxModel<>(new Tretmani().get().stream().map(tr -> new NameValue(tr.Naziv, tr.ID)).toArray(NameValue[]::new)));
        stanjeBox.setModel(new DefaultComboBoxModel<>(Arrays.stream(values()).map(stanje -> new NameValue(getStanjeName(stanje), stanje)).toArray(NameValue[]::new)));
        klijentBox.setModel(new DefaultComboBoxModel<>(new Klijenti().get().stream().map(klijent -> new NameValue(klijent.Ime, klijent.ID)).toArray(NameValue[]::new)));
        kozmeticarBox.setModel(new DefaultComboBoxModel<>(new Zaposleni().getKozmeticari().stream().map(kozmeticar -> new NameValue(kozmeticar.Ime, kozmeticar.ID)).toArray(NameValue[]::new)));
        trajanjeTxt.addKeyListener(new NumericKeyAdapter(false));
        cenaTxt.addKeyListener(new NumericKeyAdapter(true));
        datumTxt.addKeyListener(new DateKeyAdapter());
        vremeTxt.addKeyListener(new TimeKeyAdapter());
        if (tretman != null) fillInput(tretman);

        saveBtn.addActionListener(e -> Save(tretman, update));

        setVisible(true);
    }

    public ZakazaniTretman getData() {
        return new ZakazaniTretman((int) getSelectedValue(tretmanBox), txtToFloat(cenaTxt), txtToInt(trajanjeTxt), getTermin(datumTxt, vremeTxt), (EStanjeTermina) getSelectedValue(stanjeBox),
                                   (int) getSelectedValue(klijentBox), (int) getSelectedValue(kozmeticarBox), karticaLojalnostiCB.isSelected());
    }

    public void Close(Runnable update) {
        update.run();
        setVisible(false);
        dispose();
    }

    public void Save(ZakazaniTretman tretman, Runnable update) {
        if (!isInputValid(tretmanBox, klijentBox, kozmeticarBox, stanjeBox, trajanjeTxt, cenaTxt, datumTxt, vremeTxt)) showMessageDialog(this, "Neispravan unos!");
        else if (tretman == null) {
            if (!new ZakazaniTretmani().add(getData())) showMessageDialog(this, "Greška sa čuvanjem tipa!");
            else Close(update);
        } else {
            if (!new ZakazaniTretmani().edit(tretman, getData())) showMessageDialog(this, "Greška sa čuvanjem tipa!");
            else Close(update);
        }
    }

    public void fillInput(ZakazaniTretman tretman) {
        tretmanBox.setSelectedItem(new NameValue("", tretman.TretmanID));
        klijentBox.setSelectedItem(new NameValue("", tretman.KlijentID));
        kozmeticarBox.setSelectedItem(new NameValue("", tretman.KozmeticarID));
        stanjeBox.setSelectedItem(new NameValue("", tretman.Stanje));
        trajanjeTxt.setText(String.valueOf(tretman.Trajanje));
        cenaTxt.setText(String.valueOf(tretman.Cena));
        datumTxt.setText(tretman.Vreme.format(DateTimeFormatter.ofPattern("dd.MM.yyyy.")));
        vremeTxt.setText(tretman.Vreme.format(DateTimeFormatter.ofPattern("HH")) + "h");
        karticaLojalnostiCB.setSelected(tretman.KarticaLojalnosti);
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JPanel       spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 0;
        gbc.gridwidth = 5;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Cena:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 6;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label1, gbc);
        cenaTxt     = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 6;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(cenaTxt, gbc);
        final JPanel spacer2 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 10;
        gbc.gridwidth = 4;
        gbc.fill      = GridBagConstraints.VERTICAL;
        gbc.ipady     = 20;
        mainPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 11;
        gbc.weightx = 2.0;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer3, gbc);
        saveBtn = new JButton();
        saveBtn.setMaximumSize(new Dimension(78, 50));
        saveBtn.setMinimumSize(new Dimension(78, 50));
        saveBtn.setPreferredSize(new Dimension(78, 50));
        saveBtn.setText("Sačuvaj");
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 11;
        gbc.gridwidth = 2;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(saveBtn, gbc);
        final JPanel spacer4 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 12;
        gbc.gridwidth = 5;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer4, gbc);
        tretmanBox    = new JComboBox();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 1;
        gbc.gridwidth = 2;
        gbc.weightx   = 3.0;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(tretmanBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Tretman:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 1;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Trajanje:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 5;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label3, gbc);
        trajanjeTxt = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 5;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(trajanjeTxt, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Datum:");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill   = GridBagConstraints.VERTICAL;
        gbc.ipady  = 30;
        mainPanel.add(label4, gbc);
        datumTxt = new JTextField();
        datumTxt.setText("__.__.____.");
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 7;
        gbc.gridwidth = 2;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(datumTxt, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Vreme:");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 8;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill   = GridBagConstraints.VERTICAL;
        gbc.ipady  = 30;
        mainPanel.add(label5, gbc);
        final JPanel spacer5 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 1;
        gbc.gridy      = 1;
        gbc.gridheight = 9;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 20;
        mainPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 4;
        gbc.gridy      = 1;
        gbc.gridheight = 11;
        gbc.weightx    = 3.0;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer6, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Klijent:");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill   = GridBagConstraints.VERTICAL;
        gbc.ipady  = 30;
        mainPanel.add(label6, gbc);
        klijentBox    = new JComboBox();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 2;
        gbc.gridwidth = 2;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(klijentBox, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Kozmetičar:");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill   = GridBagConstraints.VERTICAL;
        gbc.ipady  = 30;
        mainPanel.add(label7, gbc);
        kozmeticarBox = new JComboBox();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 3;
        gbc.gridwidth = 2;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(kozmeticarBox, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Stanje:");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 0;
        gbc.gridy  = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill   = GridBagConstraints.VERTICAL;
        gbc.ipady  = 30;
        mainPanel.add(label8, gbc);
        stanjeBox     = new JComboBox();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 4;
        gbc.gridwidth = 2;
        gbc.weightx   = 3.0;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(stanjeBox, gbc);
        karticaLojalnostiCB = new JCheckBox();
        karticaLojalnostiCB.setText("Kartica lojalnosti");
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 9;
        gbc.gridwidth = 2;
        gbc.fill      = GridBagConstraints.BOTH;
        gbc.ipady     = 30;
        mainPanel.add(karticaLojalnostiCB, gbc);
        vremeTxt = new JTextField();
        vremeTxt.setText("0h");
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 8;
        gbc.gridwidth = 2;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(vremeTxt, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("min");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 3;
        gbc.gridy  = 5;
        gbc.fill   = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 0);
        mainPanel.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("RSD");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 3;
        gbc.gridy  = 6;
        gbc.fill   = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 0);
        mainPanel.add(label10, gbc);
        label1.setLabelFor(cenaTxt);
        label2.setLabelFor(tretmanBox);
        label3.setLabelFor(trajanjeTxt);
        label4.setLabelFor(datumTxt);
        label6.setLabelFor(klijentBox);
        label7.setLabelFor(kozmeticarBox);
        label8.setLabelFor(stanjeBox);
    }
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return mainPanel;}
}
