package rs.moma.gui.crud;

import rs.moma.entities.Tretman;
import rs.moma.gui.helper.NameValue;
import rs.moma.gui.helper.NumericKeyAdapter;
import rs.moma.managers.TipoviTretmana;
import rs.moma.managers.Tretmani;

import javax.swing.*;
import java.awt.*;

import static javax.swing.JOptionPane.showMessageDialog;
import static rs.moma.helper.DataTools.*;

public class EditTretmanForm extends JDialog {
    private JTextField           trajanjeTxt;
    private JPanel               mainPanel;
    private JTextField           nazivTxt;
    private JTextField           cenaTxt;
    private JButton              saveBtn;
    private JComboBox<NameValue> tipBox;

    public EditTretmanForm(JFrame parent, Tretman tretman, Runnable update) {
        super(parent, tretman != null ? "Tretman: " + tretman.Naziv : "Dodavanje tretmana", true);
        setMinimumSize(new Dimension(480, 450));
        setSize(700, 580);
        setLocationRelativeTo(parent);
        setContentPane(mainPanel);

        tipBox.setModel(new DefaultComboBoxModel<>(new TipoviTretmana().get().stream().map(tip -> new NameValue(tip.Tip, tip.ID)).toArray(NameValue[]::new)));
        trajanjeTxt.addKeyListener(new NumericKeyAdapter(false));
        cenaTxt.addKeyListener(new NumericKeyAdapter(true));
        if (tretman != null) fillInput(tretman);

        saveBtn.addActionListener(e -> Save(tretman, update));

        setVisible(true);
    }

    public Tretman getData() {
        return new Tretman((int) getSelectedValue(tipBox), nazivTxt.getText(), txtToFloat(cenaTxt), txtToInt(trajanjeTxt));
    }

    public void Close(Runnable update) {
        update.run();
        setVisible(false);
        dispose();
    }

    public void Save(Tretman tretman, Runnable update) {
        if (!isInputValid(nazivTxt, tipBox, cenaTxt, trajanjeTxt)) showMessageDialog(this, "Neispravan unos!");
        else if (tretman == null) {
            if (!new Tretmani().add(getData())) showMessageDialog(this, "Greška sa dodavanjem tretmana!");
            else Close(update);
        } else {
            if (!new Tretmani().edit(tretman, getData())) showMessageDialog(this, "Greška sa izmenom tretmana!");
            else Close(update);
        }
    }

    public void fillInput(Tretman tretman) {
        nazivTxt.setText(tretman.Naziv);
        tipBox.setSelectedItem(new NameValue("", tretman.TipID));
        cenaTxt.setText(String.valueOf(tretman.Cena));
        trajanjeTxt.setText(String.valueOf(tretman.Trajanje));
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JPanel       spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 0;
        gbc.gridwidth = 5;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Naziv:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 1;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label1, gbc);
        nazivTxt      = new JTextField();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 1;
        gbc.gridwidth = 2;
        gbc.weightx   = 3.0;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(nazivTxt, gbc);
        final JPanel spacer2 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 4;
        gbc.gridy      = 1;
        gbc.gridheight = 6;
        gbc.weightx    = 3.0;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 5;
        gbc.gridwidth = 3;
        gbc.fill      = GridBagConstraints.VERTICAL;
        gbc.ipady     = 20;
        mainPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 6;
        gbc.weightx = 2.0;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer4, gbc);
        saveBtn = new JButton();
        saveBtn.setMaximumSize(new Dimension(78, 50));
        saveBtn.setMinimumSize(new Dimension(78, 50));
        saveBtn.setPreferredSize(new Dimension(78, 50));
        saveBtn.setText("Sačuvaj");
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 6;
        gbc.gridwidth = 2;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(saveBtn, gbc);
        final JPanel spacer5 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 7;
        gbc.gridwidth = 5;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 1;
        gbc.gridy      = 1;
        gbc.gridheight = 4;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 20;
        mainPanel.add(spacer6, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Tip:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 2;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label2, gbc);
        tipBox        = new JComboBox();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 2;
        gbc.gridy     = 2;
        gbc.gridwidth = 2;
        gbc.weightx   = 3.0;
        gbc.anchor    = GridBagConstraints.WEST;
        gbc.fill      = GridBagConstraints.HORIZONTAL;
        mainPanel.add(tipBox, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Cena:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 3;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label3, gbc);
        cenaTxt     = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 3;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(cenaTxt, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Trajanje:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 4;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label4, gbc);
        trajanjeTxt = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 4;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(trajanjeTxt, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("RSD");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 3;
        gbc.gridy  = 3;
        gbc.fill   = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 0);
        mainPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("min");
        gbc        = new GridBagConstraints();
        gbc.gridx  = 3;
        gbc.gridy  = 4;
        gbc.fill   = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 0);
        mainPanel.add(label6, gbc);
        label1.setLabelFor(nazivTxt);
        label2.setLabelFor(tipBox);
        label3.setLabelFor(cenaTxt);
        label4.setLabelFor(trajanjeTxt);
    }
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return mainPanel;}
}
