package rs.moma.gui.crud;

import rs.moma.entities.Klijent;
import rs.moma.gui.helper.NameValue;
import rs.moma.managers.Klijenti;

import javax.swing.*;
import java.awt.*;

import static javax.swing.JOptionPane.showMessageDialog;
import static rs.moma.gui.crud.helper.EditKorisnikForm.fillInputKorisnik;
import static rs.moma.helper.DataTools.*;

public class EditKlijentForm extends JDialog {
    private JTextField           usernameTxt;
    private JTextField           lozinkaTxt;
    private JTextField           prezimeTxt;
    private JTextField           telefonTxt;
    private JTextField           adresaTxt;
    private JPanel               mainPanel;
    private JButton              saveBtn;
    private JTextField           imeTxt;
    private JComboBox<NameValue> polBox;

    public EditKlijentForm(JFrame parent, Klijent klijent, Runnable update) {
        super(parent, klijent != null ? "Klijent: " + klijent.getDisplayName() : "Dodavanje klijenta", true);
        setMinimumSize(new Dimension(480, 570));
        setSize(860, 670);
        setLocationRelativeTo(parent);
        setContentPane(mainPanel);

        fillPolBox(polBox);
        if (klijent != null) fillInputKorisnik(klijent, imeTxt, prezimeTxt, polBox, telefonTxt, adresaTxt, usernameTxt, lozinkaTxt);

        saveBtn.addActionListener(e -> Save(klijent, update));

        setVisible(true);
    }

    public Klijent getData() {
        return new Klijent(imeTxt.getText(), prezimeTxt.getText(), (EPol) getSelectedValue(polBox), telefonTxt.getText(), adresaTxt.getText(), usernameTxt.getText(), lozinkaTxt.getText());
    }

    public void Close(Runnable update) {
        update.run();
        setVisible(false);
        dispose();
    }

    public void Save(Klijent klijent, Runnable update) {
        if (!isInputValid(imeTxt, prezimeTxt, polBox, telefonTxt, adresaTxt, usernameTxt, lozinkaTxt)) showMessageDialog(this, "Neispravan unos!");
        else if (new Klijenti().isUsernameTaken(usernameTxt.getText())) showMessageDialog(this, "Uneto korisničko ime je zauzeto!");
        else if (klijent == null) {
            if (!new Klijenti().add(getData())) showMessageDialog(this, "Greška sa dodavanjem klijenta!");
            else Close(update);
        } else {
            if (!new Klijenti().edit(klijent, getData())) showMessageDialog(this, "Greška sa izmenom klijenta!");
            else Close(update);
        }
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JPanel       spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 0;
        gbc.gridwidth = 4;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 3;
        gbc.gridy      = 1;
        gbc.gridheight = 9;
        gbc.weightx    = 3.0;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 8;
        gbc.gridwidth = 3;
        gbc.fill      = GridBagConstraints.VERTICAL;
        gbc.ipady     = 20;
        mainPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 9;
        gbc.weightx = 2.0;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer4, gbc);
        saveBtn = new JButton();
        saveBtn.setMaximumSize(new Dimension(78, 50));
        saveBtn.setMinimumSize(new Dimension(78, 50));
        saveBtn.setPreferredSize(new Dimension(78, 50));
        saveBtn.setText("Sačuvaj");
        gbc       = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill  = GridBagConstraints.HORIZONTAL;
        mainPanel.add(saveBtn, gbc);
        final JPanel spacer5 = new JPanel();
        gbc           = new GridBagConstraints();
        gbc.gridx     = 0;
        gbc.gridy     = 10;
        gbc.gridwidth = 4;
        gbc.weighty   = 1.0;
        gbc.fill      = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer5, gbc);
        imeTxt      = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 1;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(imeTxt, gbc);
        final JPanel spacer6 = new JPanel();
        gbc            = new GridBagConstraints();
        gbc.gridx      = 1;
        gbc.gridy      = 1;
        gbc.gridheight = 7;
        gbc.fill       = GridBagConstraints.HORIZONTAL;
        gbc.ipadx      = 20;
        mainPanel.add(spacer6, gbc);
        prezimeTxt = new JTextField();
        gbc        = new GridBagConstraints();
        gbc.gridx  = 2;
        gbc.gridy  = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill   = GridBagConstraints.HORIZONTAL;
        mainPanel.add(prezimeTxt, gbc);
        telefonTxt = new JTextField();
        gbc        = new GridBagConstraints();
        gbc.gridx  = 2;
        gbc.gridy  = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill   = GridBagConstraints.HORIZONTAL;
        mainPanel.add(telefonTxt, gbc);
        adresaTxt  = new JTextField();
        gbc        = new GridBagConstraints();
        gbc.gridx  = 2;
        gbc.gridy  = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill   = GridBagConstraints.HORIZONTAL;
        mainPanel.add(adresaTxt, gbc);
        usernameTxt = new JTextField();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 6;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(usernameTxt, gbc);
        lozinkaTxt = new JTextField();
        gbc        = new GridBagConstraints();
        gbc.gridx  = 2;
        gbc.gridy  = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill   = GridBagConstraints.HORIZONTAL;
        mainPanel.add(lozinkaTxt, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Ime:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 1;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Prezime:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 2;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Pol:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 3;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Adresa:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 5;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Korisničko ime:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 6;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Lozinka:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 7;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label6, gbc);
        polBox      = new JComboBox();
        gbc         = new GridBagConstraints();
        gbc.gridx   = 2;
        gbc.gridy   = 3;
        gbc.weightx = 3.0;
        gbc.anchor  = GridBagConstraints.WEST;
        gbc.fill    = GridBagConstraints.HORIZONTAL;
        mainPanel.add(polBox, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Telefon:");
        gbc         = new GridBagConstraints();
        gbc.gridx   = 0;
        gbc.gridy   = 4;
        gbc.weightx = 0.5;
        gbc.anchor  = GridBagConstraints.EAST;
        gbc.fill    = GridBagConstraints.VERTICAL;
        gbc.ipady   = 30;
        mainPanel.add(label7, gbc);
        label1.setLabelFor(imeTxt);
        label2.setLabelFor(prezimeTxt);
        label3.setLabelFor(polBox);
        label4.setLabelFor(adresaTxt);
        label5.setLabelFor(usernameTxt);
        label6.setLabelFor(lozinkaTxt);
        label7.setLabelFor(telefonTxt);
    }
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return mainPanel;}
}
